//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Highscore
    {
        public int id { get; set; }
        public string name { get; set; }
        public int movements { get; set; }
        public System.TimeSpan timeToWon { get; set; }
    }
}
