//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskData
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_bar
    {
        public int id { get; set; }
        public string toDo { get; set; }
        public System.DateTime dateTime { get; set; }
        public bool done { get; set; }
        public bool expired { get; set; }
    }
}
